package app

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"sync"

	"github.com/wailsapp/wails/v2/pkg/runtime"

	"github.com/qnqatop/papeer/internal/db"
	"github.com/qnqatop/papeer/internal/llm"
	"github.com/qnqatop/papeer/internal/topics"
)

var reviewMu sync.Mutex

const reviewDisclaimer = "> **Disclaimer:** this draft was generated by an LLM from AI-generated summaries of your downloaded papers. It may contain inaccuracies, misattributions, or hallucinated claims. Verify every citation and factual statement against the source papers before using this text."

const reviewSystemPrompt = `You are an academic writing assistant helping a researcher draft a literature review. Write in formal academic style, in Markdown, WITHOUT a top-level heading (the caller adds its own heading). Cite papers inline by title and year in parentheses, not by number. Ground every claim strictly in the material provided — do not invent findings, authors, or numbers that aren't given to you. Match the dominant language of the provided summaries. Keep each response to roughly 150-350 words.`

// ReviewProgress is emitted as review:progress / review:done events.
type ReviewProgress struct {
	Stage   string `json:"stage"` // "intro", "section", "gaps", "summarizing", "done", "error"
	Current int    `json:"current"`
	Total   int    `json:"total"`
	Label   string `json:"label"`
	// Markdown holds the full assembled draft; set only on the terminal
	// "done" event.
	Markdown string `json:"markdown,omitempty"`
	// Error is set only on the terminal "error" event.
	Error string `json:"error,omitempty"`
}

// GenerateReviewDraft asynchronously drafts a literature-review Markdown
// document. If paperIDs is empty, auto-selects all downloaded papers from
// the profile. Papers are auto-summarized via the active LLM profile before
// generating the review (unless a summary already exists).
//
// Progress is reported via "review:progress" events; the finished Markdown
// (prefixed with a disclaimer) arrives in the terminal "review:done" event,
// or "review:done" with a non-empty Error field on failure. Cancel via
// CancelOperation.
func (a *App) GenerateReviewDraft(profileID int64, model string, paperIDs []int64, customPrompt string) error {
	if !reviewMu.TryLock() {
		return fmt.Errorf("review draft generation already in progress")
	}

	client, _, chosenModel, err := a.resolveLLM(model)
	if err != nil {
		reviewMu.Unlock()
		return err
	}

	if len(paperIDs) == 0 {
		papers, err := a.db.GetDownloadedPapers(profileID)
		if err != nil {
			reviewMu.Unlock()
			return err
		}
		paperIDs = make([]int64, len(papers))
		for i, p := range papers {
			paperIDs[i] = p.ID
		}
	}

	if len(paperIDs) == 0 {
		reviewMu.Unlock()
		return fmt.Errorf("no downloaded papers with PDFs")
	}

	papers, err := a.loadPapersByIDs(profileID, paperIDs)
	if err != nil {
		reviewMu.Unlock()
		return err
	}
	if len(papers) == 0 {
		reviewMu.Unlock()
		return fmt.Errorf("no valid papers found for the given IDs")
	}

	topicList, err := a.GetTopics(profileID, 0)
	if err != nil {
		reviewMu.Unlock()
		return err
	}

	gaps, err := a.db.GetCoverageGaps(profileID, 2, 15)
	if err != nil {
		reviewMu.Unlock()
		return err
	}

	ctx, cancel := context.WithCancel(a.ctx)
	a.setCancel(cancel)

	go func() {
		defer reviewMu.Unlock()
		defer func() {
			cancel()
			a.clearCancel()
		}()
		a.runReviewDraft(ctx, client, chosenModel, papers, topicList, gaps, customPrompt)
	}()

	return nil
}

func (a *App) loadPapersByIDs(profileID int64, ids []int64) ([]db.Paper, error) {
	papers := make([]db.Paper, 0, len(ids))
	for _, id := range ids {
		p, err := a.db.GetPaper(id)
		if err != nil {
			continue
		}
		if p.ProfileID != profileID {
			continue
		}
		papers = append(papers, *p)
	}
	return papers, nil
}

func (a *App) runReviewDraft(ctx context.Context, client llm.Client, model string, papers []db.Paper,
	topicList []topics.Topic, gaps []db.ExternalCitationWithMentions, customPrompt string) {

	sp := reviewSystemPrompt
	if cp := strings.TrimSpace(customPrompt); cp != "" {
		sp = cp
	}

	profileID := papers[0].ProfileID

	if err := a.ensureSummaries(ctx, client, papers, model, profileID); err != nil {
		a.emitReviewError(err)
		return
	}

	pids := make([]int64, len(papers))
	for i, p := range papers {
		pids[i] = p.ID
	}
	summariesByPaper, err := a.db.GetSummariesByPaperIDs(pids, model)
	if err != nil {
		a.emitReviewError(err)
		return
	}

	total := 1 /* intro */ + len(topicList) + 1 /* gaps */
	step := 0
	emit := func(stage, label string) {
		step++
		runtime.EventsEmit(a.ctx, "review:progress", ReviewProgress{Stage: stage, Current: step, Total: total, Label: label})
	}

	var sb strings.Builder
	sb.WriteString("# Literature Review Draft\n\n")
	sb.WriteString(reviewDisclaimer)
	sb.WriteString("\n\n")

	emit("intro", "Introduction")
	intro, err := client.Complete(ctx, sp, buildIntroPrompt(papers, topicList, summariesByPaper))
	if err != nil {
		a.emitReviewError(err)
		return
	}
	sb.WriteString("## Introduction\n\n")
	sb.WriteString(intro.Content)
	sb.WriteString("\n\n")

	byID := make(map[int64]db.Paper, len(papers))
	for _, p := range papers {
		byID[p.ID] = p
	}

	ordered := make([]topics.Topic, len(topicList))
	copy(ordered, topicList)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Size > ordered[j].Size })

	for _, t := range ordered {
		if ctx.Err() != nil {
			return
		}
		if t.Size == 0 {
			continue
		}
		emit("section", t.Label)
		res, err := client.Complete(ctx, sp, buildSectionPrompt(t, byID, summariesByPaper))
		if err != nil {
			runtime.LogWarningf(a.ctx, "review: section %q: %v", t.Label, err)
			sb.WriteString(fmt.Sprintf("## %s\n\n_Section generation failed: %v_\n\n", t.Label, err))
			continue
		}
		sb.WriteString(fmt.Sprintf("## %s\n\n", t.Label))
		sb.WriteString(res.Content)
		sb.WriteString("\n\n")
	}

	if ctx.Err() != nil {
		return
	}

	emit("gaps", "Gaps & Future Work")
	sb.WriteString("## Gaps & Future Work\n\n")
	if len(gaps) == 0 {
		sb.WriteString("No recurring uncited works were found. Fetch citation data first (Citation Graph tab) to populate this section.\n\n")
	} else {
		sb.WriteString("Works frequently referenced by papers in this corpus but not yet part of it:\n\n")
		for _, g := range gaps {
			year := "n/a"
			if g.Year != nil {
				year = fmt.Sprintf("%d", *g.Year)
			}
			sb.WriteString(fmt.Sprintf("- **%s** (%s) — mentioned by %d paper(s) in this corpus\n", g.Title, year, g.MentionCount))
		}
		sb.WriteString("\n")
	}

	runtime.EventsEmit(a.ctx, "review:done", ReviewProgress{Stage: "done", Current: total, Total: total, Markdown: sb.String()})
}

func (a *App) emitReviewError(err error) {
	runtime.LogWarningf(a.ctx, "review draft: %v", err)
	runtime.EventsEmit(a.ctx, "review:done", ReviewProgress{Stage: "error", Error: err.Error()})
}

func (a *App) ensureSummaries(ctx context.Context, client llm.Client, papers []db.Paper, model string, profileID int64) error {
	needSummaries := 0
	for _, p := range papers {
		status, err := a.db.HasActiveSummary(p.ID, model)
		if err != nil {
			return fmt.Errorf("check summary status for paper %d: %w", p.ID, err)
		}
		if status != "done" {
			needSummaries++
		}
	}

	done := 0
	for _, p := range papers {
		if ctx.Err() != nil {
			return ctx.Err()
		}

		status, err := a.db.HasActiveSummary(p.ID, model)
		if err != nil {
			return fmt.Errorf("check summary status for paper %d: %w", p.ID, err)
		}
		if status == "done" {
			continue
		}

		done++
		runtime.EventsEmit(a.ctx, "review:progress", ReviewProgress{
			Stage:   "summarizing",
			Current: done,
			Total:   needSummaries,
			Label:   p.Title,
		})

		pdfPath, err := a.db.GetPaperPDFPath(p.ID)
		if err != nil {
			runtime.LogWarningf(a.ctx, "review: no PDF for paper %q, skipping summary", p.Title)
			continue
		}

		text, err := llm.ExtractText(pdfPath)
		if err != nil {
			runtime.LogWarningf(a.ctx, "review: extract text failed for %q: %v", p.Title, err)
			continue
		}

		prompt := a.summaryPrompt(nil)
		result, err := client.Complete(ctx, prompt, text)
		if err != nil {
			runtime.LogWarningf(a.ctx, "review: summary generation failed for %q: %v", p.Title, err)
			continue
		}

		s := &db.Summary{
			PaperID:   p.ID,
			Provider:  "auto",
			Model:     model,
			Status:    "done",
			Content:   result.Content,
			TokensIn:  result.Usage.PromptTokens,
			TokensOut: result.Usage.CompletionTokens,
		}
		if err := a.db.UpsertSummary(s); err != nil {
			runtime.LogWarningf(a.ctx, "review: upsert summary for %q: %v", p.Title, err)
		}
	}
	return nil
}

func buildIntroPrompt(papers []db.Paper, topicList []topics.Topic, summariesByPaper map[int64]string) string {
	labels := make([]string, len(topicList))
	for i, t := range topicList {
		labels[i] = t.Label
	}
	return fmt.Sprintf(
		"The corpus has %d papers, automatically grouped into %d topic clusters with labels: %s.\n\n"+
			"Write a short introduction (2-3 paragraphs) framing the overall research area covered by this corpus and previewing the themes below.",
		len(papers), len(topicList), strings.Join(labels, "; "))
}

const maxSectionPapers = 25

func buildSectionPrompt(t topics.Topic, byID map[int64]db.Paper, summariesByPaper map[int64]string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(
		"Write a literature review section synthesizing the following papers, automatically grouped under the theme %q (top terms: %s):\n\n",
		t.Label, strings.Join(t.TopTerms, ", ")))

	n := 0
	for _, id := range t.PaperIDs {
		p, ok := byID[id]
		if !ok {
			continue
		}
		if n >= maxSectionPapers {
			sb.WriteString(fmt.Sprintf("...and %d further papers in this cluster (omitted for brevity).\n", len(t.PaperIDs)-n))
			break
		}
		n++
		year := "n/a"
		if p.Year != nil {
			year = fmt.Sprintf("%d", *p.Year)
		}
		summary := summariesByPaper[p.ID]
		if summary == "" {
			summary = p.Abstract
		}
		if len(summary) > 600 {
			summary = summary[:600] + "..."
		}
		sb.WriteString(fmt.Sprintf("- %s (%s)\n  Summary: %s\n\n", p.Title, year, summary))
	}
	return sb.String()
}
